# Generated by Django 5.2.8 on 2025-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="title",
            field=models.CharField(default="New Chat", max_length=255),
        ),
    ]
