# Generated by Django 5.2.7 on 2025-10-22 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("bio", models.TextField(blank=True, default="", null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
